name: Test Job

on:
  push:
    paths:
      - path1/**
      - path2/**

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          echo "Test"
