name: Test Job

on:
  push:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    outputs:
      TEST_1_VALUE: ${{ steps.test-1.outputs.TEST_1_VALUE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sleep 10 seconds
        run: |
          sleep 10

      - name: Run tests 1
        id: test-1
        run: |
          echo "TEST_1_VALUE=Test1" >> $GITHUB_OUTPUT

  test-job-2:
    runs-on: ubuntu-latest
    needs: test-job-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests 2
        run: |
          echo ${{ needs.test-job-1.outputs.TEST_1_VALUE }}

      - name: Fail the job
        run: |
          exit 1
